version: '3'

services:
  db:
    image: postgres:14.3  
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: ecommerce-db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data